name: barber_center
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
#flutter build appbundle
  # arch -x86_64 pod install
  # arch -x86_64 pod update
  # flutter build apk --split-per-abi
  # flutter pub run flutter_launcher_icons
  # flutter build web
# firebase deploy

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get:
  gap: ^2.0.1
  dependencies:
  provider: ^6.0.5
  flutter_svg_provider: ^1.0.3
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  cloud_firestore: ^4.4.3
  firebase_database: ^10.0.7
  fluttertoast: ^8.2.1
  firebase_storage: ^11.0.9
  carousel_slider: ^4.2.1
  fluentui_icons: ^1.0.0
  flutter_localization: ^0.1.10

#image
  photo_view: ^0.14.0
  image_cropper: ^3.0.1
  image_picker: ^0.8.6
  cached_network_image: ^3.2.1
  flutter_native_image: ^0.0.6+1
  permission_handler: ^9.2.0

  #CALENDAR
  flutter_calendar_week: ^3.0.0

  #icon
  flutter_launcher_icons: ^0.11.0
  # flutter pub run flutter_launcher_icons





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_bk.png"
  image_path_ios: "assets/images/icon_bk.png"
  remove_alpha_ios: true
